apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: shiny-app
build:
  artifacts:
  - image: shiny-example-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/shiny-pod.yaml
    - k8s/shiny-svc.yaml
